controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_default:
    path: /
    controller: App\Controller\HomeController::index

# config/routes.yaml

app_search:
    path: /search
    controller: App\Controller\SearchController::search
